# ML Models
#### Using Main branch past preprocessed data

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import BernoulliNB
from xgboost import XGBClassifier
from lightgbm.sklearn import LGBMClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

import credit_data

import warnings
warnings.filterwarnings("ignore")

In [7]:
train_data, test_data, train_label, test_label = credit_data.load_data()
print(train_data.shape, test_data.shape, train_label.shape, test_label.shape)

(15906, 67) (6818, 67) (15906, 1) (6818, 1)

In [8]:
models = [
    ('Logistic', LogisticRegression()),
    ('KNN', KNeighborsClassifier(16)),
    ('SVM', SVC(kernel='rbf', C=100, gamma=0.01)),
    ('DecisionTree', DecisionTreeClassifier(random_state = 0, max_depth = 4)),
    ('RandomForest', RandomForestClassifier(random_state = 0, n_estimators = 100, max_depth = 6)),
    ('NaiveBayes', BernoulliNB(alpha=10)),
    ('XGBoost', XGBClassifier(seed = 0, n_estimators = 200, max_depth = 2, verbosity=0)),
    ('LightGBM', LGBMClassifier(random_state=0, n_estimators = 200, max_depth = 2))]

In [9]:
# for name, model in models:
#     model.fit(train_data, train_label)
#     print(f'{name}: ', accuracy_score(model.predict(test_data), test_label))

In [10]:
# clf = LinearDiscriminantAnalysis()
# clf.fit(train_data.todense(), train_label)
# print('Linear Discriminat Analysis:', accuracy_score(clf.predict(test_data), test_label))

In [11]:
train_data

<15906x67 sparse matrix of type '<class 'numpy.float64'>'
	with 270402 stored elements in Compressed Sparse Row format>

In [12]:
#### NGBoost
from ngboost import NGBClassifier
from ngboost.distns import k_categorical, Bernoulli

ngb_cat = NGBClassifier(Dist=k_categorical(3), verbose=False) # tell ngboost that there are 3 possible outcomes
_ = ngb_cat.fit(train_data, train_label) # Y should have only 3 values: {0,1,2}

In [13]:
ngb_cat.predict(test_data)

array([2, 2, 2, ..., 2, 1, 2])

In [14]:
ngb_pred_test = ngb_cat.predict(test_data)

In [15]:
accuracy_score(ngb_pred_test, test_label)

0.6915517747139923

In [21]:
round(accuracy_score(ngb_cat.predict(train_data), train_label),4)

0.6898

In [17]:
ngb_cat.predict_proba(test_data)

array([[0.11615147, 0.23131703, 0.6525315 ],
       [0.13784527, 0.23860816, 0.62354657],
       [0.1160482 , 0.19928395, 0.68466785],
       ...,
       [0.12981473, 0.18012702, 0.69005824],
       [0.06763661, 0.62196931, 0.31039408],
       [0.12861968, 0.20450865, 0.66687167]])

In [18]:
ngb_cat.pred_dist(test_data).params

{'p0': array([0.11615147, 0.13784527, 0.1160482 , ..., 0.12981473, 0.06763661,
        0.12861968]),
 'p1': array([0.23131703, 0.23860816, 0.19928395, ..., 0.18012702, 0.62196931,
        0.20450865]),
 'p2': array([0.6525315 , 0.62354657, 0.68466785, ..., 0.69005824, 0.31039408,
        0.66687167])}

In [19]:
#### Scores 
from ngboost.scores import LogScore, CRPScore 

NGBClassifier(Dist = k_categorical(3), Score = LogScore, verbose=False).fit(train_data, train_label)

NGBClassifier(random_state=RandomState(MT19937) at 0x103E7FB40, verbose=False)

In [38]:
train_soso = pd.read_csv('train_othrs.csv')
train_soso.head()

,index,age,begin_month,car,career,cluster,days_income,days_unemployed,edu_type,email,...,income_type,month_birth,month_unemployed,occyp_type,phone,reality,week_birth,week_unemployed,work_phone,credit
0,0,38,6.0,1,12,30,10.882416,9190,1,1,...,1,7.0,6.0,1,1,1,1.0,0.0,1,1.0
1,1,31,5.0,1,4,15,19.156347,9840,2,2,...,1,7.0,4.0,2,1,2,1.0,1.0,1,1.0
2,2,52,22.0,2,12,8,19.131840,14653,1,1,...,2,0.0,8.0,3,2,2,2.0,1.0,1,2.0
3,3,41,37.0,1,5,30,11.786962,12996,2,1,...,1,10.0,1.0,4,2,2,3.0,0.0,1,0.0
4,4,41,26.0,2,5,5,9.187959,12932,1,1,...,3,9.0,11.0,3,1,2,0.0,3.0,1,2.0

In [39]:
train_new_label = train_new[['credit']]
train_new = train_new.drop(['credit'], axis =1)

KeyError: "None of [Index(['credit'], dtype='object')] are in the [columns]"

In [35]:
train_new_label

       credit
0         1.0
1         1.0
2         2.0
3         0.0
4         2.0
...       ...
26452     1.0
26453     2.0
26454     2.0
26455     2.0
26456     2.0

[26457 rows x 1 columns]

In [33]:
train_new

,index,age,begin_month,car,career,cluster,days_income,days_unemployed,edu_type,email,...,income_total,income_type,month_birth,month_unemployed,occyp_type,phone,reality,week_birth,week_unemployed,work_phone
0,0,38,6.0,1,12,30,10.882416,9190,1,1,...,202500.0,1,7.0,6.0,1,1,1,1.0,0.0,1
1,1,31,5.0,1,4,15,19.156347,9840,2,2,...,247500.0,1,7.0,4.0,2,1,2,1.0,1.0,1
2,2,52,22.0,2,12,8,19.131840,14653,1,1,...,450000.0,2,0.0,8.0,3,2,2,2.0,1.0,1
3,3,41,37.0,1,5,30,11.786962,12996,2,1,...,202500.0,1,10.0,1.0,4,2,2,3.0,0.0,1
4,4,41,26.0,2,5,5,9.187959,12932,1,1,...,157500.0,3,9.0,11.0,3,1,2,0.0,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26452,26452,33,2.0,1,5,26,15.999431,10095,2,1,...,225000.0,3,6.0,0.0,6,1,1,1.0,2.0,1
26453,26453,41,47.0,1,6,23,10.131712,12816,1,1,...,180000.0,2,5.0,7.0,1,1,2,0.0,2.0,1
26454,26454,27,25.0,2,5,10,24.179549,8067,2,1,...,292500.0,2,0.0,4.0,6,1,1,0.0,0.0,1
26455,26455,27,59.0,1,0,33,16.679672,10038,3,1,...,171000.0,2,2.0,10.0,2,1,2,1.0,2.0,1
26456,26456,53,9.0,1,2,9,3.935478,18556,2,1,...,81000.0,2,4.0,6.0,12,1,1,3.0,2.0,1

In [34]:
ngb_cat = NGBClassifier(Dist=k_categorical(3), verbose=False) # tell ngboost that there are 3 possible outcomes
_ = ngb_cat.fit(train_new, train_new_label) # Y should have only 3 values: {0,1,2}

IndexError: arrays used as indices must be of integer (or boolean) type

In [ ]:
accuracy_score(ngb_pred_test, test_label)